name: testnet

services:
  miner:
    build: .
    command: ./start-miner.sh --test
    network_mode: "host"
    env_file: .env.test
    volumes:
      - ./:/app
      - ${BT_WALLET_PATH:-~/.bittensor/wallets}:/root/.bittensor/wallets/
    working_dir: /app
    deploy:
      restart_policy:
        condition: unless-stopped

  validator:
    build: .
    command: ./start-validator.sh --test --proxy.port 10914
    network_mode: "host"
    env_file: .env.test
    volumes:
      - ./:/app
      - ${BT_WALLET_PATH:-~/.bittensor/wallets}:/root/.bittensor/wallets/
    working_dir: /app
    deploy:
      restart_policy:
        condition: unless-stopped
